<script lang="ts">
export default {
  name: "LoginView",

}

</script>

<template>
  <div class="content-container">
    <div class="login-card">
      <h1>Login</h1>
      <FormKit type="form" id="login-submit" submit-label="Login" @submit="" :submit-attrs="{ignore: false}">
        <FormKit type="text" name="username" id="username" validation="required|not:Admin" label="Username"
                 placeholder="Insert your username" />
        <FormKit type="password" name="password" id="password" validation="required|not:Admin" label="Password"
                 placeholder="Insert your password" />
      </FormKit>
      <small>Don't have an account? <RouterLink to="/register">Make one here!</RouterLink></small>
    </div>
  </div>
</template>

<style>

.login-card {
  transition: 1s ease-in 0.5s 1 scale-up-center;
  -webkit-animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  color: var(--text);
  margin: 10% 10px 10px;
  background-color: var(--wbg);
  width: fit-content;
  border-radius: 6px;
  border: 4px solid var(--wborder);
  padding: 20px;
  filter: drop-shadow(10px 10px 0px var(--wborder));
}

#username,
#password {
  background-color: transparent;
  border: 2px solid var(--wborder);
  border-radius: 5px;
  width: 30vh;
  resize: none;
  font-family: inherit;
  margin-top: 10px;
  margin-bottom: 10px;
}

[data-type="submit"] .formkit-input {
  color: var(--text);
  font-family: inherit;
  background: var(--wborder) !important;
  border-radius: 5px;
}

/* ----------------------------------------------
  * Generated by Animista on 2023-5-19 14:41:29
  * Licensed under FreeBSD License.
  * See http://animista.net/license for more info.
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */

/**
  * ----------------------------------------
  * animation scale-up-center
  * ----------------------------------------
  */
@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }

  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}

@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }

  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}

@media (min-width: 1024px) {
  .about {
    min-height: 100vh;
    display: flex;
    align-items: center;
  }
}
</style>
