<script setup>
    import axios from 'axios';

    const castRangeToNumber = (node) => {
    // We add a check to add the cast only to range inputs
    if (node.props.type !== 'range') return
    node.hook.input((value, next) => next(Number(value)))
    }

    async function createTask(fields){
        let res = await axios.post('http://localhost:25565/taskadd', fields)
        alert(JSON.stringify(fields))
    }
</script>

<template>
    <div class="taskcard">
        <h1>New Task</h1>
        <FormKit type="form"
        id="tasksubmit"
        submit-label="Add"
        @submit="createTask"
        :submit-attrs="{
            ignore: false
        }">
            <FormKit
                type="text"
                name="taskname"
                id="taskname"
                validation="required|not:Admin"
                label="Task name"
                placeholder="School"
            />
            <FormKit
                type="textarea"
                name="taskdesc"
                id="taskdesc"
                validation="required|not:Admin"
                label="Task description"
                placeholder="Do homework"
            />
        </FormKit>
    </div>    
</template>

<style>
    .taskcard {
        transition: 1s ease-in 0.5s 1 scale-up-center;
        -webkit-animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	        animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
        color: var(--text);
        margin: 10px;
        background-color: var(--wbg);
        width: fit-content;
        padding: 10px;
        border-radius: 6px;
        border: 4px solid var(--wborder);
        padding: 20px;
        filter: drop-shadow(10px 10px 0px var(--wborder));
    }

    #taskname, #taskdesc {
        background-color: transparent;
        border: 2px solid var(--wborder);
        border-radius: 5px;
        width: 30vh;
        resize: none;
        font-family: inherit;
        margin-top: 10px;
        margin-bottom: 10px;
    }

    [data-type="submit"] .formkit-input {
        color: var(--text);
        font-family: inherit;
        background: var(--wborder) !important;
        border-radius: 5px;
    }

    /* ----------------------------------------------
 * Generated by Animista on 2023-5-19 14:41:29
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}
@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
            transform: scale(0.5);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}

    
</style>