<script setup>
import axios from 'axios';

async function createTask(fields) {
  const timeElapsed = Date.now();
  const today = new Date(timeElapsed);
  fields.taskdate = today
  await axios.post('http://localhost:25565/taskadd', fields,{ withCredentials: true })
  window.location.reload()
}
</script>

<script>
export default {
  data() {
    return {
      tasks: null
    }
  },
  async created() {
    this.tasks = await this.getTasks()
  },
  methods: {
    async getTasks() {
      let tasksget = await fetch('http://localhost:25565/taskgetall', { credentials: "include", })
      const tasks = await tasksget.json()
      return tasks
    },
    async deleteTask(taskid){
      await axios.post('http://localhost:25565/taskdelete', { taskid: taskid }, { withCredentials: true })
    }
  }
}
</script>

<template>
  <div class="contentcontainer">
    <div class="taskcard">
      <h1>New Task</h1>
      <FormKit type="form" id="tasksubmit" submit-label="Add" @submit="createTask" :submit-attrs="{
        ignore: false
      }">
        <FormKit type="text" name="taskname" id="taskname" validation="required|not:Admin" label="Task name"
          placeholder="School" />
        <FormKit type="textarea" name="taskdesc" id="taskdesc" validation="required|not:Admin" label="Task description"
          placeholder="Do homework" />
      </FormKit>
    </div>
    <div class="taskcontainer">
      <div class="taskindiv" v-for="(task) in tasks" :key="task.taskid">
        <h1>{{ task.taskname }}</h1>
        <p>{{ task.taskdescription }}</p>
        <p>{{ task.taskdate }}</p>
        <button @click="deleteTask(task.taskid)">Delete</button>
      </div>
    </div>
  </div>
</template>

<style>
.contentcontainer {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  flex-direction: column;
  align-content: center;
}

.taskcontainer {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  flex-direction: row;
  align-content: center;
}

.taskindiv {
  transition: 1s ease-in 0.5s 1 scale-up-center;
  -webkit-animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  color: var(--text);
  margin: 14px;
  background-color: var(--wbg);
  width: fit-content;
  padding: 10px;
  border-radius: 6px;
  border: 4px solid var(--wborder);
  padding: 20px;
  filter: drop-shadow(10px 10px 0px var(--wborder));
}

/**/
.taskcard {
  transition: 1s ease-in 0.5s 1 scale-up-center;
  -webkit-animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  color: var(--text);
  margin: 10px;
  background-color: var(--wbg);
  width: fit-content;
  padding: 10px;
  border-radius: 6px;
  border: 4px solid var(--wborder);
  padding: 20px;
  filter: drop-shadow(10px 10px 0px var(--wborder));
  align-self: center;
}

#taskname,
#taskdesc {
  background-color: transparent;
  border: 2px solid var(--wborder);
  border-radius: 5px;
  width: 30vh;
  resize: none;
  font-family: inherit;
  margin-top: 10px;
  margin-bottom: 10px;
}

[data-type="submit"] .formkit-input {
  color: var(--text);
  font-family: inherit;
  background: var(--wborder) !important;
  border-radius: 5px;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-5-19 14:41:29
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }

  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}

@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
  }

  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
</style>
  